# Site Settings
url: https://ercong21.github.io
base_ulr: ""
title: Ercong Nie [ɚ'tsʰʊŋ, niɛ]
subtitle: "Ercong's Homepage"
description: "Ercong Nie [ɚ'tsʰʊŋ, niɛ]"
keywords: 聂耳聪, Ercong Nie, ercong21
timezone: Asia/Shanghai
encoding: "utf-8"
SEOTitle: Ercong Nie's Homepage
repository: ercong21/ercong21.github.io

# Author Settings
author: Ercong Nie
github_username: ercong21
location: Munich, Germany
email: nie@cis.lmu.de

# Navigation Settings
navs:
  -
    href: /
    label: Home
  - href: /news/
    label: News
  - href: /publications/
    label: Publications
  - href: /teaching/
    label: Teaching
  - href: /grants/
    label: Grants
  - href: ../files/Resume_Nie.pdf
    label: CV

# RSS Settings
RSS: true
subscribe_rss: /feed.xml

# Build Settings
highlighter: rouge
paginate: 10
permalink: pretty
gems: [jekyll-paginate]
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
        
# Markdown Settings
markdown: kramdown
kramdown:
    input: GFM
mathjax: true

# Comments Settings
comments_provider: gitment
gitment:
    owner: ercong21
    repo: blog-comments
    oauth:
        client_id: 5818ceff784afe05d31c
        client_secret: dc7e8efc044c7194cf453740f82c646aa998f206
